server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
          locator:
            enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes: #路由配置
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service  #lb://serviceName是spring cloud gateway在微服务中自动为我们创建的负载均衡uri
          predicates:
            - Path=/payment/findById/**   #断言,路径相匹配的进行路由

        - id: payment_routh2  #路由的ID，没有固定的规则要求唯一，建议配合服务名
          #uri: http://localhost:8001 #匹配后提供服务的地址
          uri: lb://cloud-payment-service
          predicates: #Predicate就是为了实现一组匹配规则，让请求过来找到对应的Route进行处理
            - Path=/payment/lb/**   #断言，路由相匹配的进行路由转发
            #- After=2021-05-16T14:22:14.669+08:00[Asia/Shanghai]
            #- Cookie=username,zc    #并且Cookie是username=zc才能访问
            #- Before=2021-05-16T14:22:14.669+08:00[Asia/Shanghai]
            #- Between=2021-05-16T14:22:14.669+08:00[Asia/Shanghai] ,  2024-05-16T14:22:14.669+08:00[Asia/Shanghai]
            #- Header=X-Request-Id, \d+   #请求头中要有X-Request-Id属性并且值为整数的正则表达式


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true #表示注册进eureka
      fetch-registry: true #表示可以在eureka服务端抓取注册信息
      defaultZone: http://eureka7001.com:7001/eureka