server:
  port: 8888
spring:  datasource:    druid:      url:  jdbc:mysql://localhost:3306/mhis_db?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: root
      password: 888888
  jpa:    show-sql: true
